import type { Metadata } from "next";
import { Manrope } from "next/font/google";

import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth"

import "./globals.css";

const ManropeFont = Manrope({
  subsets: ["latin", "vietnamese"],
  weight: ["200", "300", "400", "500", "600", "700", "800"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang="en">
      <body
        className={`${ManropeFont.className} antialiased select-none`}
      >
        {children}
      </body>
    </html>
    </SessionProvider>
  );
}
